export const CONTENTFUL_SPACE_ID = "t5i7iuryq60u";
export const CONTENTFUL_DELIVERY_ACCESS_TOKEN =
  "6Ffi2n4m1lWhLzylHaukbOdCdd1CLkqPQ1ty7PENImQ";
export const CONTENTFUL_MANAGEMENT_ACCESS_TOKEN =
  "CFPAT-axVhG0qjr0k2KxXHQgd4Ak6E41BWSMbf96M-rM58kf4";
